const dyr = [
    ['apekatt', 'apekatten'],
    ['bille', 'billen'],
    ['bjørn', 'bjørnen'],
    ['blekksprut', 'blekkspruten'],
    ['ekorn', 'ekornet'],
    ['elg', 'elgen'],
    ['fisk', 'fisken'],
    ['frosk', 'frosken'],
    ['fugl', 'fuglen'],
    ['gås', 'gåsen'],
    ['gaupe', 'gaupen'],
    ['geit', 'geita'],
    ['gris', 'grisen'],
    ['hest', 'hesten'],
    ['hjort', 'hjorten'],
    ['hund', 'hunden'],
    ['hval', 'hvalen'],
    ['hyene', 'hyenen'],
    ['katt', 'katten'],
    ['koie', 'koien'],
    ['krabbe', 'krabben'],
    ['ku', 'kuen'],
    ['kylling', 'kyllingen'],
    ['laks', 'laksen'],
    ['lama', 'lamaen'],
    ['løve', 'løven'],
    ['mark', 'marken'],
    ['mus', 'musen'],
    ['orm', 'ormen'],
    ['ørn', 'ørnen'],
    ['oter', 'oteren'],
    ['panda', 'pandaen'],
    ['rev', 'reven'],
    ['rotte', 'rotta'],
    ['sau', 'sauen'],
    ['sel', 'selen'],
    ['slange', 'slangen'],
    ['snegle', 'sneglen'],
    ['svale', 'svalen'],
    ['tiger', 'tigeren'],
    ['torsk', 'torsken'],
    ['ulv', 'ulven'],
    ['ål', 'ålen'],
]

const fabeldyr = [
    ['alv', 'alven'],
    ['demon', 'demonen'],
    ['drage', 'dragen'],
    ['dverg', 'dvergen'],
    ['fe', 'feen'],
    ['gnom', 'gnomen'],
    ['griff', 'griffen'],
    ['gud', 'guden'],
    ['havfrue', 'havfruen'],
    ['heks', 'heksen'],
    ['hulder', 'huldra'],
    ['kentaur', 'kentauren'],
    ['kjempe', 'kjempen'],
    ['satyr', 'satyren'],
    ['sfnisk', 'sfnisken'],
    ['troll', 'trollet'],
    ['trollmann', 'trollmannen'],
    ['vampyr', 'vampyren'],
    ['varulv', 'varulven'],
]

const mennesker = [
    ['dame', 'dama'],
    ['danske' 'dansken'],
    ['dronning', 'dronningen'],
    ['finne', 'finnen'],
    ['fyr', 'fyren'],
    ['gutt', 'gutten'],
    ['jeger', 'jegeren'],
    ['jente', 'jenta'],
    ['kar', 'karen'],
    ['knekt', 'knekten'],
    ['konge', 'kongen'],
    ['konsulent', 'konsulenten'],
    ['mann', 'mannen'],
    ['pirat', 'piraten'],
    ['prins', 'prinsen'],
    ['rådgiver', 'rådgiveren'],
    ['sjørøver', 'sjørøveren'],
    ['svenske', 'svensken'],
]

const ting = [
    ['drone', 'dronen'],
    ['robot', 'roboten'],
    ['androide', 'androiden'],
]

const subjekter = [
    ...dyr,
    ...mennesker,
    ...fabeldyr,
    ...ting,
];

export const ubestemteSubjekter: string[] = subjekter.map(([ubestemt]) => ubestemt);
export const bestemteSubjekter: string[] = subjekter.map(([ubestemt, bestemt]) => bestemt);

export default subjekter;